"""
SQLAlchemy ORM models — all tables for Somm v2.0.

All primary keys are TEXT UUIDs (generated by the application), except
chartier_library which mirrors the xlsx row number (INTEGER).

Uses Optional[T] rather than T | None to stay compatible with Python 3.9,
because SQLAlchemy 2.0 evaluates annotation strings at runtime.
"""

from datetime import datetime
from typing import List, Optional

from sqlalchemy import Boolean, ForeignKey, Integer, Text
from sqlalchemy.orm import Mapped, mapped_column, relationship

from db import Base


# ---------------------------------------------------------------------------
# Auth + user tables
# ---------------------------------------------------------------------------


class User(Base):
    __tablename__ = "users"

    id: Mapped[str] = mapped_column(Text, primary_key=True)
    email: Mapped[str] = mapped_column(Text, unique=True, nullable=False)
    display_name: Mapped[Optional[str]] = mapped_column(Text)
    role: Mapped[str] = mapped_column(Text, nullable=False)           # 'admin' | 'user'
    status: Mapped[str] = mapped_column(Text, nullable=False)         # 'active' | 'revoked'
    created_at: Mapped[Optional[str]] = mapped_column(Text)
    last_login_at: Mapped[Optional[str]] = mapped_column(Text)

    sessions: Mapped[List["Session"]] = relationship(back_populates="user")
    magic_link_tokens: Mapped[List["MagicLinkToken"]] = relationship(back_populates="user")
    invites_created: Mapped[List["Invite"]] = relationship(
        foreign_keys="Invite.created_by", back_populates="created_by_user"
    )
    chats: Mapped[List["Chat"]] = relationship(back_populates="user")
    preferences: Mapped[List["Preference"]] = relationship(back_populates="user")
    saved_pairings: Mapped[List["SavedPairing"]] = relationship(back_populates="user")
    audit_events: Mapped[List["AuditLog"]] = relationship(back_populates="actor")


class Invite(Base):
    __tablename__ = "invites"

    id: Mapped[str] = mapped_column(Text, primary_key=True)
    token: Mapped[str] = mapped_column(Text, unique=True, nullable=False)
    email: Mapped[Optional[str]] = mapped_column(Text)                # pins invite to one address
    created_by: Mapped[Optional[str]] = mapped_column(Text, ForeignKey("users.id"))
    expires_at: Mapped[Optional[str]] = mapped_column(Text)
    used_at: Mapped[Optional[str]] = mapped_column(Text)
    used_by_user_id: Mapped[Optional[str]] = mapped_column(Text, ForeignKey("users.id"))

    created_by_user: Mapped[Optional["User"]] = relationship(
        foreign_keys=[created_by], back_populates="invites_created"
    )


class MagicLinkToken(Base):
    __tablename__ = "magic_link_tokens"

    id: Mapped[str] = mapped_column(Text, primary_key=True)
    user_id: Mapped[str] = mapped_column(Text, ForeignKey("users.id"), nullable=False)
    token_hash: Mapped[str] = mapped_column(Text, nullable=False)     # SHA-256; never store raw
    created_at: Mapped[Optional[str]] = mapped_column(Text)
    expires_at: Mapped[Optional[str]] = mapped_column(Text)           # 15 min from creation
    used_at: Mapped[Optional[str]] = mapped_column(Text)

    user: Mapped["User"] = relationship(back_populates="magic_link_tokens")


class Session(Base):
    __tablename__ = "sessions"

    id: Mapped[str] = mapped_column(Text, primary_key=True)
    user_id: Mapped[str] = mapped_column(Text, ForeignKey("users.id"), nullable=False)
    session_token_hash: Mapped[str] = mapped_column(Text, unique=True, nullable=False)
    created_at: Mapped[Optional[str]] = mapped_column(Text)
    expires_at: Mapped[Optional[str]] = mapped_column(Text)           # 30-day rolling
    user_agent: Mapped[Optional[str]] = mapped_column(Text)
    ip: Mapped[Optional[str]] = mapped_column(Text)

    user: Mapped["User"] = relationship(back_populates="sessions")


# ---------------------------------------------------------------------------
# Chat + messages
# ---------------------------------------------------------------------------


class Chat(Base):
    __tablename__ = "chats"

    id: Mapped[str] = mapped_column(Text, primary_key=True)
    user_id: Mapped[str] = mapped_column(Text, ForeignKey("users.id"), nullable=False)
    title: Mapped[Optional[str]] = mapped_column(Text)                # auto-generated from first Q
    created_at: Mapped[Optional[str]] = mapped_column(Text)
    updated_at: Mapped[Optional[str]] = mapped_column(Text)
    archived_at: Mapped[Optional[str]] = mapped_column(Text)          # soft delete

    user: Mapped["User"] = relationship(back_populates="chats")
    messages: Mapped[List["Message"]] = relationship(back_populates="chat")


class Message(Base):
    __tablename__ = "messages"

    id: Mapped[str] = mapped_column(Text, primary_key=True)
    chat_id: Mapped[str] = mapped_column(Text, ForeignKey("chats.id"), nullable=False)
    role: Mapped[str] = mapped_column(Text, nullable=False)           # 'user' | 'assistant'
    content: Mapped[Optional[str]] = mapped_column(Text)
    attachments_json: Mapped[Optional[str]] = mapped_column(Text)     # screenshot refs for debug
    created_at: Mapped[Optional[str]] = mapped_column(Text)

    chat: Mapped["Chat"] = relationship(back_populates="messages")


# ---------------------------------------------------------------------------
# Preferences
# ---------------------------------------------------------------------------


class Preference(Base):
    __tablename__ = "preferences"

    id: Mapped[str] = mapped_column(Text, primary_key=True)
    user_id: Mapped[str] = mapped_column(Text, ForeignKey("users.id"), nullable=False)
    kind: Mapped[Optional[str]] = mapped_column(Text)                 # wine|grape|region|style|ingredient|other
    value: Mapped[Optional[str]] = mapped_column(Text)
    strictness: Mapped[str] = mapped_column(Text, nullable=False)     # 'strict' | 'soft'
    notes: Mapped[Optional[str]] = mapped_column(Text)
    created_at: Mapped[Optional[str]] = mapped_column(Text)

    user: Mapped["User"] = relationship(back_populates="preferences")


# ---------------------------------------------------------------------------
# Saved pairings
# ---------------------------------------------------------------------------


class SavedPairing(Base):
    __tablename__ = "saved_pairings"

    id: Mapped[str] = mapped_column(Text, primary_key=True)
    user_id: Mapped[str] = mapped_column(Text, ForeignKey("users.id"), nullable=False)
    source: Mapped[Optional[str]] = mapped_column(Text)               # 'chartier' | 'chat' | 'custom'
    source_ref: Mapped[Optional[str]] = mapped_column(Text)           # chartier_library.id or chats.id
    wine: Mapped[Optional[str]] = mapped_column(Text)
    dish: Mapped[Optional[str]] = mapped_column(Text)
    molecule_logic: Mapped[Optional[str]] = mapped_column(Text)
    wine_examples: Mapped[Optional[str]] = mapped_column(Text)
    user_notes: Mapped[Optional[str]] = mapped_column(Text)
    is_private: Mapped[bool] = mapped_column(Boolean, default=True, nullable=False)
    # tried_at ships in v2.0 schema so v2.1 ratings can land without a migration (§13 decision 4).
    tried_at: Mapped[Optional[str]] = mapped_column(Text)
    created_at: Mapped[Optional[str]] = mapped_column(Text)

    user: Mapped["User"] = relationship(back_populates="saved_pairings")


# ---------------------------------------------------------------------------
# Chartier library (read-only; synced from xlsx)
# ---------------------------------------------------------------------------


class ChartierEntry(Base):
    __tablename__ = "chartier_library"

    id: Mapped[int] = mapped_column(Integer, primary_key=True)        # mirrors xlsx row order
    wine_style: Mapped[Optional[str]] = mapped_column(Text)
    dish: Mapped[Optional[str]] = mapped_column(Text)
    molecule_logic: Mapped[Optional[str]] = mapped_column(Text)
    wine_examples: Mapped[Optional[str]] = mapped_column(Text)
    imported_at: Mapped[Optional[str]] = mapped_column(Text)
    checksum: Mapped[Optional[str]] = mapped_column(Text)             # detects changes on re-sync


# ---------------------------------------------------------------------------
# Audit log
# ---------------------------------------------------------------------------


class AuditLog(Base):
    __tablename__ = "audit_log"

    id: Mapped[str] = mapped_column(Text, primary_key=True)
    actor_user_id: Mapped[Optional[str]] = mapped_column(Text, ForeignKey("users.id"))
    # e.g. 'invite_created' | 'user_revoked' | 'login' | 'chartier_synced'
    action: Mapped[Optional[str]] = mapped_column(Text)
    target_type: Mapped[Optional[str]] = mapped_column(Text)
    target_id: Mapped[Optional[str]] = mapped_column(Text)
    created_at: Mapped[Optional[str]] = mapped_column(Text)
    metadata_json: Mapped[Optional[str]] = mapped_column(Text)

    actor: Mapped[Optional["User"]] = relationship(back_populates="audit_events")
